name: Get Sentiment and update GitHub page

on:
  schedule:
  - cron: "30 2/4 * * *" # Runs every 4 hours (IST: 12 AM, 4 AM, 8 AM, 12 PM, 4 PM, 8 PM)

  workflow_dispatch:
jobs:
  fetch-data-update-dashboard:
    runs-on: ubuntu-latest

    env: # shared across this job
      python_version: "3.13"

    permissions:
      contents: write # required to push changes to the repo

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
          python-version: ${{ env.python_version }}

      - name: Install necessary libraries using uv
        run: make install
      - name: Install Google Sheets libs
        run: |
          pip install gspread oauth2client
        
      - name: Execute main python file
        env:
          GOOGLE: ${{ secrets.GOOGLE }}
        run: make run

      - name: Execute python script to update sentiment page
        run: make dashboard

      - name: save updated db file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add .

          CHANGES=$(git status --porcelain)

          if [ -z "$CHANGES" ]; then
            echo "✅ No changes"
          else
            git commit -m "update db file using GH Actions"
            git push
          fi
